name: Build

concurrency:
 group: ${{ github.workflow }}-${{ github.ref }}
 cancel-in-progress: true

on:
 push:
    branches:
      - 'master'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
 pull_request:
    paths-ignore:
      - '**.md'

env:
 DOCKERHUB_SLUG: anonaddy/anonaddy

jobs:
 build:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.title=AnonAddy
            org.opencontainers.image.description=Anonymous Email Forwarding
            org.opencontainers.image.vendor=CrazyMax
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
